apiVersion: v1
kind: Pod
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  containers:
    - name: sonarqube
      image: sonarqube:10.6.0-community
      ports:
        - containerPort: 9000
      env:
        - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
          value: "false"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
          cpu: "1"
      volumeMounts:
        - name: sonarqube-data
          mountPath: /opt/sonarqube/data
        - name: sonarqube-logs
          mountPath: /opt/sonarqube/logs
  volumes:
    - name: sonarqube-data
      emptyDir: {}
    - name: sonarqube-logs
      emptyDir: {}
